version: '3.1'

volumes:
  vol-database:

services:
  database:
    image: mysql:latest
    hostname: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: notapp
      MYSQL_PASSWORD: notapp.pass
      MYSQL_DATABASE: notapp-db
    volumes:
      - vol-database:/var/lib/mysql
      - ./notapp-infraestructure/src/main/resources/sql:/docker-entrypoint-initdb.d
    ports:
      - 6500:3306

  app:
    profiles: [ "app" ]
    image: maven:3-eclipse-temurin-22-alpine
    depends_on:
      - database
    working_dir: /app
    command: >
      sh -c "echo 'Building the application...'
      && mvn -U clean install -DskipTests=true 
      && echo 'Launching the application...'
      && java -jar notapp-infraestructure/target/notapp-infraestructure-v1.0.0-SNAPSHOT.jar --spring.profiles.active=docker"
    volumes:
      - ./:/app
    ports:
      - 6000:8080